### ISSUE TITLE
关于Evolution.Framework重新生成卡死的问题

### ISSUE THREAD

**Issue by withlin** [CAH-FlyChen/Evolution.Framework#1]
项目重新生成后会卡死， 原因是 BuildPost.cmd 里是用的绝对路径，把Evolution.Plugins.Area 的 BuildPost.cmd 改为：

- xcopy /y bin\Debug\netcoreapp1.0\Evolution.Plugins.Area.dll ..\Evolution.Web\Plugins\Evolution.Plugins.Area\bin\
- xcopy /y bin\Debug\netcoreapp1.0\Evolution.Plugins.Area.pdb ..\Evolution.Web\Plugins\Evolution.Plugins.Area\bin\
- xcopy /E /y Views\*.* ..\Evolution.Web\Plugins\Evolution.Plugins.Area\Views\*.*

即可。

**Comment by CAH-FlyChen** [comment]
已经按照意见修复
